### ISSUE TITLE
[Bug] Potions are not moving across conveyor belts. (Critical Priority)

### ISSUE THREAD

**Issue by IndefinitelyAMsPipisAppriciatorIG** [stathampen/GalwayGJDec20#29]
Issue:
Potions are not moving across the conveyor belts, preventing the core gameplay mechanics from functioning.

Steps To Reproduce:
1. Open unity to a scene with a bottle and a conveyor.
2. Orient the bottle to be above the conveyor.
3. Press play

Result:
The potion falls onto the conveyor belt, but will not be moved along by the conveyor belt.

**Comment by ReshiIRE** [comment]
This is solved, this was down to a prefab having a conveyor movement speed set to zero.
