### ISSUE TITLE
[Bug] Potions are not deleting themselves after falling or explosion. (Critical Priority)

### ISSUE THREAD

**Issue by IndefinitelyAMsPipisAppriciatorIG** [stathampen/GalwayGJDec20#30]
Issue:
Potions are not deleting themselves after falling or exploding. Potions that are not deleted continue to interact with the rest of the environment, causing issues like multiple permanent explosion effects replaying on the player's screen, or blocking the player's movement on the ground.

Steps to Reproduce:
1. Open unity with a scene that has a bottle and potion pourers.
2. Press the play button.
3. Pick up the potion
4. Place the potion under a potion pourer.
5. Pick up the potion again.
6. Place the potion under a potion pourer of a different colour
7. Pick up the potion again.
8. Pkace the potion under a potion pourer of any colour

Result:
The potion is overmixed and generates an explosion effect, but remains in the game and can continue to be interacted with.

**Comment by ReshiIRE** [comment]
This was called by a floor prefab not having a `Floor` tag.
