### ISSUE TITLE
[Design] Level 1

### ISSUE THREAD

**Issue by IndefinitelyAMsPipisAppriciatorIG** [stathampen/GalwayGJDec20#35]
Level 1 is currently set as a prefab but is missing the following features:

Level controller that sets the level goal to delivering 3 green potions.
Instruction Panel telling the player to pick up the potions once the machine pours a liquid in, and place them on the exit conveyor.
Level Music.

Please amend as these things are added to the prefab.

**Comment by ReshiIRE** [comment]
Level controller is completed and working.

**Comment by ReshiIRE** [comment]
Level music has been added, and we have an intro instruction panel; I will close this, but we can go back to tutorials if require .
